// shared/languages.js
// Sistema multiidioma completo para StoryOwl V1
// Usado tanto en frontend como en backend

const LANGS = {
  es: {
    flag: '🇪🇸', code: 'ES', name: 'Español',
    // Formulario
    heroTitle: 'Crea el cuento', heroEm: 'de tu peque',
    formTitle: 'Personaliza', formTitleEm: 'el protagonista',
    formSub: 'Cada detalle importa. Así el cuento será realmente suyo.',
    labelNombre: '¿Cómo se llama?', placeholderNombre: 'Ej: Sofía, Lucas, Martina...',
    labelEdad: '¿Cuántos años tiene?', labelEdadSub: 'El tono del cuento se adapta a esta edad',
    labelGenero: 'Es un...', btnNina: '👧 Niña', btnNino: '👦 Niño', btnSorpresa: '🌟 Sorpresa',
    labelPiel: 'Tono de piel', labelPelo: 'Color de pelo',
    labelTipoPelo: 'Tipo de pelo', btnLiso: '〰 Liso', btnRizado: '✦ Rizado',
    btnOndulado: '〜 Ondulado', btnMuyCorto: '✂ Muy corto', btnTrenzas: '💈 Trenzas',
    labelOjos: 'Color de ojos',
    labelGafas: '¿Lleva gafas?', btnGafasNo: '😊 No', btnGafasSi: '🤓 Sí',
    labelPecas: '¿Tiene pecas?', btnPecasNo: '✨ No', btnPecasSi: '🌟 Sí',
    secCuento: '✨ El cuento',
    labelTema: '¿De qué trata la aventura?', placeholderTema: 'Ej: encontrar un dragón perdido, salvar el bosque mágico...',
    labelPersonaje: '¿Quién le acompaña?', placeholderPersonaje: 'Ej: su perro Toby, una hada traviesa, un robot amigo...',
    secEstilo: '🎨 Estilo de ilustración',
    secDedicatoria: '💌 Dedicatoria personal',
    labelDedicatoriaTexto: 'Palabras para tu peque', labelOpcional: '(opcional)',
    placeholderDedicatoria: 'Ej: Para mi niña Sofía, que llena nuestra vida de magia...',
    btnGenerar: '🦉 ¡Crear el cuento!',
    estilos: [
      { id: 'pixar',    nombre: 'Pixar',     desc: '3D vivo y colorido' },
      { id: 'acuarela', nombre: 'Acuarela',  desc: 'Suave y soñador' },
      { id: 'comic',    nombre: 'Cómic',     desc: 'Dinámico y divertido' },
      { id: 'clasico',  nombre: 'Clásico',   desc: 'Cuento tradicional' },
      { id: 'manga',    nombre: 'Manga',      desc: 'Estilo japonés' }
    ],
    // Estados de generación
    estadoPersonajes: '🦉 El búho está creando los personajes...',
    estadoCuento: '🦉 El búho está escribiendo el cuento...',
    estadoImagenes: '🎨 Generando las ilustraciones...',
    estadoPDF: '📄 Componiendo la preview...',
    estadoListo: '✅ ¡Tu preview está lista!',
    // CTA
    ctaListo: '¡Tu cuento está listo!',
    ctaSub: 'Descarga el PDF de alta calidad, sin marca de agua, listo para imprimir y regalar.',
    btnPDF: '📄 PDF Digital', precioPDF: '4,99 €',
    btnLibro: '📚 Libro Físico', precioLibro: '24,99 €',
    btnCrearOtro: '✨ Crear otro cuento',
    // Viewer
    subtituloPreview: 'Vista previa · Descarga el PDF para la versión completa',
    watermark: 'Vista previa · StoryOwl · Vista previa · StoryOwl',
    finSub: 'Un cuento creado especialmente para',
    backPhrase: 'Que la magia de las historias\nte acompañe siempre.',
    dedicatoriaPara: 'Para',
    // PDF
    pdfPagina: 'PÁGINA',
    pdfCreadoPara: 'Un cuento creado para',
    pdfContraFrase: 'Que la magia de las historias\nte acompañe siempre.',
    finTexto: '¡FIN!',
    backLink: '← Volver a StoryOwl',
  },
  en: {
    flag: '🇬🇧', code: 'EN', name: 'English',
    heroTitle: 'Create the story', heroEm: 'of your little one',
    formTitle: 'Customize', formTitleEm: 'the main character',
    formSub: 'Every detail matters. This way the story will truly be theirs.',
    labelNombre: 'What is their name?', placeholderNombre: 'E.g.: Emma, Jack, Lily...',
    labelEdad: 'How old are they?', labelEdadSub: 'The story tone adapts to this age',
    labelGenero: 'They are a...', btnNina: '👧 Girl', btnNino: '👦 Boy', btnSorpresa: '🌟 Surprise',
    labelPiel: 'Skin tone', labelPelo: 'Hair color',
    labelTipoPelo: 'Hair type', btnLiso: '〰 Straight', btnRizado: '✦ Curly',
    btnOndulado: '〜 Wavy', btnMuyCorto: '✂ Very short', btnTrenzas: '💈 Braids',
    labelOjos: 'Eye color',
    labelGafas: 'Wears glasses?', btnGafasNo: '😊 No', btnGafasSi: '🤓 Yes',
    labelPecas: 'Has freckles?', btnPecasNo: '✨ No', btnPecasSi: '🌟 Yes',
    secCuento: '✨ The story',
    labelTema: 'What is the adventure about?', placeholderTema: 'E.g.: finding a lost dragon, saving the magic forest...',
    labelPersonaje: 'Who joins them?', placeholderPersonaje: 'E.g.: their dog Buddy, a mischievous fairy, a robot friend...',
    secEstilo: '🎨 Illustration style',
    secDedicatoria: '💌 Personal dedication',
    labelDedicatoriaTexto: 'Words for your little one', labelOpcional: '(optional)',
    placeholderDedicatoria: 'E.g.: For my girl Emma, who fills our lives with magic...',
    btnGenerar: '🦉 Create the story!',
    estilos: [
      { id: 'pixar',    nombre: 'Pixar',      desc: '3D vivid & colorful' },
      { id: 'acuarela', nombre: 'Watercolor', desc: 'Soft & dreamy' },
      { id: 'comic',    nombre: 'Comic',      desc: 'Dynamic & fun' },
      { id: 'clasico',  nombre: 'Classic',    desc: 'Traditional storybook' },
      { id: 'manga',    nombre: 'Manga',       desc: 'Japanese style' }
    ],
    estadoPersonajes: '🦉 The owl is creating the characters...',
    estadoCuento: '🦉 The owl is writing the story...',
    estadoImagenes: '🎨 Generating the illustrations...',
    estadoPDF: '📄 Composing the preview...',
    estadoListo: '✅ Your preview is ready!',
    ctaListo: 'Your story is ready!',
    ctaSub: 'Download the high-quality PDF, watermark-free, ready to print and gift.',
    btnPDF: '📄 Digital PDF', precioPDF: '€4.99',
    btnLibro: '📚 Physical Book', precioLibro: '€24.99',
    btnCrearOtro: '✨ Create another story',
    subtituloPreview: 'Preview · Download the full PDF for the complete version',
    watermark: 'Preview · StoryOwl · Preview · StoryOwl',
    finSub: 'A story created especially for',
    backPhrase: 'May the magic of stories\nbe with you always.',
    dedicatoriaPara: 'For',
    pdfPagina: 'PAGE',
    pdfCreadoPara: 'A story created for',
    pdfContraFrase: 'May the magic of stories\nbe with you always.',
    finTexto: 'THE END',
    backLink: '← Back to StoryOwl',
  },
  de: {
    flag: '🇩🇪', code: 'DE', name: 'Deutsch',
    heroTitle: 'Erstelle das Buch', heroEm: 'für dein Kind',
    formTitle: 'Gestalte', formTitleEm: 'die Hauptfigur',
    formSub: 'Jedes Detail zählt. So wird die Geschichte wirklich einzigartig.',
    labelNombre: 'Wie heißt sie/er?', placeholderNombre: 'Z.B.: Emma, Luca, Mia...',
    labelEdad: 'Wie alt ist sie/er?', labelEdadSub: 'Der Ton der Geschichte passt sich dem Alter an',
    labelGenero: 'Es ist ein...', btnNina: '👧 Mädchen', btnNino: '👦 Junge', btnSorpresa: '🌟 Überraschung',
    labelPiel: 'Hautton', labelPelo: 'Haarfarbe',
    labelTipoPelo: 'Haartyp', btnLiso: '〰 Glatt', btnRizado: '✦ Lockig',
    btnOndulado: '〜 Wellig', btnMuyCorto: '✂ Sehr kurz', btnTrenzas: '💈 Zöpfe',
    labelOjos: 'Augenfarbe',
    labelGafas: 'Trägt Brille?', btnGafasNo: '😊 Nein', btnGafasSi: '🤓 Ja',
    labelPecas: 'Hat Sommersprossen?', btnPecasNo: '✨ Nein', btnPecasSi: '🌟 Ja',
    secCuento: '✨ Die Geschichte',
    labelTema: 'Worum geht es im Abenteuer?', placeholderTema: 'Z.B.: einen verlorenen Drachen finden, den Zauberwald retten...',
    labelPersonaje: 'Wer begleitet sie/ihn?', placeholderPersonaje: 'Z.B.: ihr Hund Bello, eine freche Fee, ein Roboterfreund...',
    secEstilo: '🎨 Illustrationsstil',
    secDedicatoria: '💌 Persönliche Widmung',
    labelDedicatoriaTexto: 'Worte für dein Kind', labelOpcional: '(optional)',
    placeholderDedicatoria: 'Z.B.: Für meine Emma, die unser Leben mit Magie füllt...',
    btnGenerar: '🦉 Geschichte erstellen!',
    estilos: [
      { id: 'pixar',    nombre: 'Pixar',     desc: '3D lebendig & bunt' },
      { id: 'acuarela', nombre: 'Aquarell',  desc: 'Sanft & verträumt' },
      { id: 'comic',    nombre: 'Comic',     desc: 'Dynamisch & lustig' },
      { id: 'clasico',  nombre: 'Klassisch', desc: 'Traditionelles Bilderbuch' },
      { id: 'manga',    nombre: 'Manga',      desc: 'Japanischer Stil' }
    ],
    estadoPersonajes: '🦉 Die Eule erstellt die Charaktere...',
    estadoCuento: '🦉 Die Eule schreibt die Geschichte...',
    estadoImagenes: '🎨 Illustrationen werden generiert...',
    estadoPDF: '📄 Vorschau wird zusammengestellt...',
    estadoListo: '✅ Deine Vorschau ist fertig!',
    ctaListo: 'Dein Buch ist fertig!',
    ctaSub: 'Lade das hochauflösende PDF herunter — ohne Wasserzeichen, druckfertig.',
    btnPDF: '📄 PDF Digital', precioPDF: '€4,99',
    btnLibro: '📚 Gedrucktes Buch', precioLibro: '€24,99',
    btnCrearOtro: '✨ Neue Geschichte erstellen',
    subtituloPreview: 'Vorschau · PDF für die vollständige Version herunterladen',
    watermark: 'Vorschau · StoryOwl · Vorschau · StoryOwl',
    finSub: 'Eine Geschichte, die speziell für',
    backPhrase: 'Möge die Magie der Geschichten\nimmer bei dir sein.',
    dedicatoriaPara: 'Für',
    pdfPagina: 'SEITE',
    pdfCreadoPara: 'Eine Geschichte für',
    pdfContraFrase: 'Möge die Magie der Geschichten\nimmer bei dir sein.',
    finTexto: 'ENDE',
    backLink: '← Zurück zu StoryOwl',
  },
  fr: {
    flag: '🇫🇷', code: 'FR', name: 'Français',
    heroTitle: "Crée le livre", heroEm: "de ton enfant",
    formTitle: 'Personnalise', formTitleEm: 'le personnage principal',
    formSub: "Chaque détail compte. Ainsi l'histoire sera vraiment la sienne.",
    labelNombre: "Comment s'appelle-t-il/elle?", placeholderNombre: 'Ex: Emma, Lucas, Chloé...',
    labelEdad: "Quel âge a-t-il/elle?", labelEdadSub: "Le ton de l'histoire s'adapte à cet âge",
    labelGenero: "C'est un...", btnNina: '👧 Fille', btnNino: '👦 Garçon', btnSorpresa: '🌟 Surprise',
    labelPiel: 'Teint', labelPelo: 'Couleur des cheveux',
    labelTipoPelo: 'Type de cheveux', btnLiso: '〰 Lisses', btnRizado: '✦ Bouclés',
    btnOndulado: '〜 Ondulés', btnMuyCorto: '✂ Très court', btnTrenzas: '💈 Tresses',
    labelOjos: 'Couleur des yeux',
    labelGafas: 'Porte des lunettes?', btnGafasNo: '😊 Non', btnGafasSi: '🤓 Oui',
    labelPecas: 'A des taches de rousseur?', btnPecasNo: '✨ Non', btnPecasSi: '🌟 Oui',
    secCuento: "✨ L'histoire",
    labelTema: "De quoi parle l'aventure?", placeholderTema: 'Ex: trouver un dragon perdu, sauver la foret magique...',
    labelPersonaje: "Qui l'accompagne?", placeholderPersonaje: 'Ex: son chien Filou, une fee espiegle, un robot ami...',
    secEstilo: "🎨 Style d'illustration",
    secDedicatoria: '💌 Dedicace personnelle',
    labelDedicatoriaTexto: 'Mots pour ton enfant', labelOpcional: '(optionnel)',
    placeholderDedicatoria: 'Ex: Pour ma petite Emma, qui remplit notre vie de magie...',
    btnGenerar: '🦉 Creer le livre!',
    estilos: [
      { id: 'pixar',    nombre: 'Pixar',      desc: '3D vif & colore' },
      { id: 'acuarela', nombre: 'Aquarelle',  desc: 'Doux & onirique' },
      { id: 'comic',    nombre: 'BD',         desc: 'Dynamique & amusant' },
      { id: 'clasico',  nombre: 'Classique',  desc: 'Livre traditionnel' },
      { id: 'manga',    nombre: 'Manga',       desc: 'Style japonais' }
    ],
    estadoPersonajes: '🦉 Le hibou cree les personnages...',
    estadoCuento: "🦉 Le hibou ecrit l'histoire...",
    estadoImagenes: '🎨 Generation des illustrations...',
    estadoPDF: '📄 Composition de la previsualisation...',
    estadoListo: '✅ Ta previsualisation est prete!',
    ctaListo: 'Ton livre est pret!',
    ctaSub: 'Telecharge le PDF haute qualite, sans filigrane, pret a imprimer et offrir.',
    btnPDF: '📄 PDF Digital', precioPDF: '€4,99',
    btnLibro: '📚 Livre physique', precioLibro: '€24,99',
    btnCrearOtro: '✨ Creer une autre histoire',
    subtituloPreview: 'Apercu · Telechargez le PDF pour la version complete',
    watermark: 'Apercu · StoryOwl · Apercu · StoryOwl',
    finSub: 'Une histoire creee specialement pour',
    backPhrase: 'Que la magie des histoires\nte soit toujours fidele.',
    dedicatoriaPara: 'Pour',
    pdfPagina: 'PAGE',
    pdfCreadoPara: 'Une histoire creee pour',
    pdfContraFrase: 'Que la magie des histoires\nte soit toujours fidele.',
    finTexto: 'FIN',
    backLink: '← Retour a StoryOwl',
  },
  pt: {
    flag: '🇵🇹', code: 'PT', name: 'Português',
    heroTitle: 'Crie o livro', heroEm: 'do seu pequeno',
    formTitle: 'Personalize', formTitleEm: 'o personagem principal',
    formSub: 'Cada detalhe importa. Assim a historia sera verdadeiramente dele.',
    labelNombre: 'Como se chama?', placeholderNombre: 'Ex: Sofia, Lucas, Ana...',
    labelEdad: 'Quantos anos tem?', labelEdadSub: 'O tom da historia adapta-se a esta idade',
    labelGenero: 'E um...', btnNina: '👧 Menina', btnNino: '👦 Menino', btnSorpresa: '🌟 Surpresa',
    labelPiel: 'Tom de pele', labelPelo: 'Cor do cabelo',
    labelTipoPelo: 'Tipo de cabelo', btnLiso: '〰 Liso', btnRizado: '✦ Cacheado',
    btnOndulado: '〜 Ondulado', btnMuyCorto: '✂ Muito curto', btnTrenzas: '💈 Trancas',
    labelOjos: 'Cor dos olhos',
    labelGafas: 'Usa oculos?', btnGafasNo: '😊 Nao', btnGafasSi: '🤓 Sim',
    labelPecas: 'Tem sardas?', btnPecasNo: '✨ Nao', btnPecasSi: '🌟 Sim',
    secCuento: '✨ A historia',
    labelTema: 'Sobre o que e a aventura?', placeholderTema: 'Ex: encontrar um dragao perdido, salvar a floresta magica...',
    labelPersonaje: 'Quem o acompanha?', placeholderPersonaje: 'Ex: seu cachorro Rex, uma fada travessa, um robo amigo...',
    secEstilo: '🎨 Estilo de ilustracao',
    secDedicatoria: '💌 Dedicatoria pessoal',
    labelDedicatoriaTexto: 'Palavras para o seu pequeno', labelOpcional: '(opcional)',
    placeholderDedicatoria: 'Ex: Para a minha Sofia, que enche a nossa vida de magia...',
    btnGenerar: '🦉 Criar a historia!',
    estilos: [
      { id: 'pixar',    nombre: 'Pixar',       desc: '3D vivo e colorido' },
      { id: 'acuarela', nombre: 'Aquarela',    desc: 'Suave e sonhador' },
      { id: 'comic',    nombre: 'Quadrinhos',  desc: 'Dinamico e divertido' },
      { id: 'clasico',  nombre: 'Classico',    desc: 'Livro tradicional' },
      { id: 'manga',    nombre: 'Manga',        desc: 'Estilo japones' }
    ],
    estadoPersonajes: '🦉 A coruja esta a criar os personagens...',
    estadoCuento: '🦉 A coruja esta a escrever a historia...',
    estadoImagenes: '🎨 A gerar as ilustracoes...',
    estadoPDF: '📄 A compor a pre-visualizacao...',
    estadoListo: '✅ A tua pre-visualizacao esta pronta!',
    ctaListo: 'O teu livro esta pronto!',
    ctaSub: 'Descarrega o PDF de alta qualidade, sem marca de agua, pronto para imprimir e oferecer.',
    btnPDF: '📄 PDF Digital', precioPDF: '€4,99',
    btnLibro: '📚 Livro Fisico', precioLibro: '€24,99',
    btnCrearOtro: '✨ Criar outra historia',
    subtituloPreview: 'Pre-visualizacao · Descarregue o PDF para a versao completa',
    watermark: 'Pre-visualizacao · StoryOwl · Pre-visualizacao · StoryOwl',
    finSub: 'Uma historia criada especialmente para',
    backPhrase: 'Que a magia das historias\nte acompanhe sempre.',
    dedicatoriaPara: 'Para',
    pdfPagina: 'PAGINA',
    pdfCreadoPara: 'Uma historia criada para',
    pdfContraFrase: 'Que a magia das historias\nte acompanhe sempre.',
    finTexto: 'FIM',
    backLink: '← Voltar ao StoryOwl',
  }
};

module.exports = { LANGS };
